In [1]:
#import dependencies
import pandas as pd
import csv 

# File to Load (Remember to Change These)
file = "drought_data/Fires_data.csv"

# Read Purchasing File and store into Pandas data frame
fires_df = pd.read_csv(file)
fires_df

,X,Y,OBJECTID,FIRE_ID,ASMNT_TYPE,PRE_ID,POST_ID,NODATA_THRESHOLD,LOW_THRESHOLD,MODERATE_THRESHOLD,...,GREENNESS_THRESHOLD,IG_DATE,ACRES,IRWINID,MAP_ID,MAP_PROG,PERIM_ID,DNBR_OFFST,DNBR_STDDV,COMMENTS
0,-161.627876,62.013298,1,AK6201316162819840703,Extended (SS),NaN,507601719850724,9999,370,125,...,9999,1984/07/03 00:00:00+00,8479,NaN,4555,MTBS,NaN,-9999,-9999,NaN
1,-157.536525,63.757053,2,AK6375715753719840609,Extended (SS),NaN,507501519850802,9999,450,300,...,9999,1984/06/09 00:00:00+00,37083,NaN,4546,MTBS,NaN,-9999,-9999,NaN
2,-155.028811,63.794900,3,AK6379515502919840623,Extended (SS),NaN,507401519850726,9999,430,115,...,9999,1984/06/23 00:00:00+00,1399,NaN,4551,MTBS,NaN,-9999,-9999,NaN
3,-157.526912,63.929845,4,AK6393015752719840606,Extended (SS),NaN,507501519850802,9999,475,335,...,9999,1984/06/06 00:00:00+00,10243,NaN,4545,MTBS,NaN,-9999,-9999,Hard to determine fire perimeter
4,-144.673271,64.482310,5,AK6448214467319840607,Initial (SS),NaN,506801519840713,9999,550,165,...,9999,1984/06/07 00:00:00+00,1897,NaN,4534,MTBS,5.066015e+14,-9999,-9999,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25609,-107.926112,43.788093,25610,WY4379410794120180726,Initial,803603020180711,803603020180727,-970,40,200,...,-150,2018/07/26 00:00:00+00,2444,6F8F8FF2-6B6D-47E6-9876-57603F2F502A,10011374,MTBS,NaN,22,9,NaN
25610,-107.783680,43.790439,25611,WY4381010781320180813,Initial,803603020180812,803603020180913,-970,40,250,...,-150,2018/08/13 00:00:00+00,6973,B837C791-75C4-4A86-B174-6925188F8A43,10011325,MTBS,NaN,45,12,NaN
25611,-107.801509,44.158711,25612,WY4410810779120180708,Initial,803602920180625,803602920180812,-970,10,9999,...,-150,2018/07/08 00:00:00+00,43872,902BC4C0-7DE1-4B1C-9DCE-99EED76312BD,10011328,MTBS,NaN,19,25,This mapping included the Apache East fire. Th...
25612,-107.668955,44.198938,25613,WY4421310768820180614,Initial,803602920180609,803602920180625,-970,50,285,...,-150,2018/06/14 00:00:00+00,2009,07A83678-540D-4D0F-A864-446A75A6DFD0,10011337,MTBS,NaN,20,7,NaN
25613,-108.928560,44.461476,25614,WY4446210893620180812,Initial,803702920180803,803702920180904,-970,55,260,...,-150,2018/08/12 00:00:00+00,1837,AF65922F-6C0E-42AF-83E5-A32000624E58,10011341,MTBS,NaN,12,14,NaN

In [3]:
print(list(fires_df.columns))

['X', 'Y', 'OBJECTID', 'FIRE_ID', 'ASMNT_TYPE', 'PRE_ID', 'POST_ID', 'NODATA_THRESHOLD', 'LOW_THRESHOLD', 'MODERATE_THRESHOLD', 'HIGH_THRESHOLD', 'LATITUDE', 'LONGITUDE', 'FIRE_TYPE', 'FIRE_NAME', 'GREENNESS_THRESHOLD', 'IG_DATE', 'ACRES', 'IRWINID', 'MAP_ID', 'MAP_PROG', 'PERIM_ID', 'DNBR_OFFST', 'DNBR_STDDV', 'COMMENTS']

In [2]:
wildfire_df = fires_df.loc[fires_df["FIRE_TYPE"] == "Wildfire", :]
wildfire_df

,X,Y,OBJECTID,FIRE_ID,ASMNT_TYPE,PRE_ID,POST_ID,NODATA_THRESHOLD,LOW_THRESHOLD,MODERATE_THRESHOLD,...,GREENNESS_THRESHOLD,IG_DATE,ACRES,IRWINID,MAP_ID,MAP_PROG,PERIM_ID,DNBR_OFFST,DNBR_STDDV,COMMENTS
0,-161.627876,62.013298,1,AK6201316162819840703,Extended (SS),NaN,507601719850724,9999,370,125,...,9999,1984/07/03 00:00:00+00,8479,NaN,4555,MTBS,NaN,-9999,-9999,NaN
1,-157.536525,63.757053,2,AK6375715753719840609,Extended (SS),NaN,507501519850802,9999,450,300,...,9999,1984/06/09 00:00:00+00,37083,NaN,4546,MTBS,NaN,-9999,-9999,NaN
2,-155.028811,63.794900,3,AK6379515502919840623,Extended (SS),NaN,507401519850726,9999,430,115,...,9999,1984/06/23 00:00:00+00,1399,NaN,4551,MTBS,NaN,-9999,-9999,NaN
3,-157.526912,63.929845,4,AK6393015752719840606,Extended (SS),NaN,507501519850802,9999,475,335,...,9999,1984/06/06 00:00:00+00,10243,NaN,4545,MTBS,NaN,-9999,-9999,Hard to determine fire perimeter
4,-144.673271,64.482310,5,AK6448214467319840607,Initial (SS),NaN,506801519840713,9999,550,165,...,9999,1984/06/07 00:00:00+00,1897,NaN,4534,MTBS,5.066015e+14,-9999,-9999,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25609,-107.926112,43.788093,25610,WY4379410794120180726,Initial,803603020180711,803603020180727,-970,40,200,...,-150,2018/07/26 00:00:00+00,2444,6F8F8FF2-6B6D-47E6-9876-57603F2F502A,10011374,MTBS,NaN,22,9,NaN
25610,-107.783680,43.790439,25611,WY4381010781320180813,Initial,803603020180812,803603020180913,-970,40,250,...,-150,2018/08/13 00:00:00+00,6973,B837C791-75C4-4A86-B174-6925188F8A43,10011325,MTBS,NaN,45,12,NaN
25611,-107.801509,44.158711,25612,WY4410810779120180708,Initial,803602920180625,803602920180812,-970,10,9999,...,-150,2018/07/08 00:00:00+00,43872,902BC4C0-7DE1-4B1C-9DCE-99EED76312BD,10011328,MTBS,NaN,19,25,This mapping included the Apache East fire. Th...
25612,-107.668955,44.198938,25613,WY4421310768820180614,Initial,803602920180609,803602920180625,-970,50,285,...,-150,2018/06/14 00:00:00+00,2009,07A83678-540D-4D0F-A864-446A75A6DFD0,10011337,MTBS,NaN,20,7,NaN
25613,-108.928560,44.461476,25614,WY4446210893620180812,Initial,803702920180803,803702920180904,-970,55,260,...,-150,2018/08/12 00:00:00+00,1837,AF65922F-6C0E-42AF-83E5-A32000624E58,10011341,MTBS,NaN,12,14,NaN